# -*- coding: utf-8 -*-
"""
Generate src/generated/constants.h from the decompiled ActionScript sources.

Every `static const NAME:int|uint|Number|Boolean = expr;` of the game classes is
emitted as a C++ constexpr inside a namespace named after the class
(Drawing::imgTitle, Library::MUSIC_TITLE, ...). Library `:Class` constants that
point at embedded fDat/fAni/snd/DB assets are turned into their asset number,
so e.g. Library::btn == the N of Library_fDat<N>.

`public var NAME:Array = new Array(a, b, ...)` tables whose items all resolve to
numbers (LOADLOGOIMG, LOADLOGOIMGINDEX, SNDEFFECTNAME, ...) are emitted as
`inline const std::vector<int>`.

Keeping this generated (instead of hand-copied) means the C++ port can never
drift from the original numbers.
"""
import glob
import json
import os
import re

AS_DIR = 'extracted/scripts/scripts/com/fazecat/web/paladog'
OUT = 'native_port/src/generated/constants.h'
OUT_JSON = 'native_port/src/generated/constants.json'
# Every non-asset class that declares static consts. Namespaces are named k<Class>
# (kDrawing::imgTitle, kLibrary::MUSIC_TITLE, ...).
CLASSES = sorted(
    os.path.basename(p)[:-3] for p in glob.glob(f'{AS_DIR}/*.as')
    if not os.path.basename(p).startswith(('Library_', 'Logo'))
    and 'static const' in open(p, encoding='utf-8').read()
)

CONST_RE = re.compile(r'static const (\w+):(\w+) = ([^;]+);')
ARRAY_RE = re.compile(r'public var (\w+):Array = new Array\(([^;]*)\);')
ASSET_RE = re.compile(r'^Library_(fDat|fAni|snd|DB)(\d+)$')


def load(cls):
    src = open(f'{AS_DIR}/{cls}.as', encoding='utf-8').read()
    # FFDec wraps very long lines in the middle of member accesses ("Drawing\n   .imgX")
    return re.sub(r'(\w)\s*\n\s*\.(\w)', r'\1.\2', src)


def main():
    raw = {c: load(c) for c in CLASSES}
    values = {c: {} for c in CLASSES}       # resolved numeric values
    pending = {c: [] for c in CLASSES}      # (name, type, expr)
    asset_kind = {}                          # Library const name -> kind

    for cls, src in raw.items():
        for name, typ, expr in CONST_RE.findall(src):
            expr = expr.strip()
            if typ == 'Class':
                m = ASSET_RE.match(expr)
                if m:
                    values[cls][name] = int(m.group(2))
                    asset_kind[name] = m.group(1)
                continue
            if typ not in ('int', 'uint', 'Number', 'Boolean'):
                continue
            pending[cls].append((name, typ, expr))

    types = {}

    def resolve(cls, expr):
        expr = expr.replace('true', 'True').replace('false', 'False')

        def sub(m):
            ident = m.group(0)
            if '.' in ident:
                c, n = ident.split('.', 1)
                if c in values and n in values[c]:
                    return repr(values[c][n])
                raise KeyError(ident)
            if ident in ('True', 'False'):
                return ident
            if ident in values[cls]:
                return repr(values[cls][ident])
            for c in CLASSES:
                if ident in values[c]:
                    return repr(values[c][ident])
            raise KeyError(ident)

        py = re.sub(r'[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)?', sub, expr)
        py = py.replace('Math.PI', '3.141592653589793')
        return eval(py, {'__builtins__': {}})

    # iterate until everything resolves (constants may reference later ones)
    for _ in range(10):
        progress = False
        for cls in CLASSES:
            left = []
            for name, typ, expr in pending[cls]:
                try:
                    v = resolve(cls, expr)
                except KeyError:
                    left.append((name, typ, expr))
                    continue
                if typ in ('int', 'uint'):
                    v = int(v)
                values[cls][name] = v
                types[(cls, name)] = typ
                progress = True
            pending[cls] = left
        if not progress:
            break
    unresolved = [(c, n, e) for c in CLASSES for n, _, e in pending[c]]

    arrays = {c: [] for c in CLASSES}
    skipped_arrays = []
    for cls, src in raw.items():
        for name, items in ARRAY_RE.findall(src):
            parts = [p.strip() for p in items.split(',')] if items.strip() else []
            if len(parts) < 2:
                continue  # `new Array(N)` is a sized allocation, not a table
            try:
                vals = [int(resolve(cls, p)) for p in parts]
            except (KeyError, SyntaxError, NameError, TypeError):
                skipped_arrays.append(f'{cls}.{name}')
                continue
            arrays[cls].append((name, vals))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('// GENERATED by native_port/tools/gen_constants.py - do not edit.\n')
        f.write('// Source: decompiled Paladog ActionScript (all classes with static consts).\n')
        f.write('#pragma once\n#include <vector>\n\n')
        info = {'consts': {}, 'tables': {}}
        for cls in CLASSES:
            f.write(f'namespace k{cls} {{\n')
            info['consts'][cls] = {}
            for name, v in values[cls].items():
                typ = types.get((cls, name))
                if typ == 'Boolean':
                    f.write(f'constexpr bool {name} = {"true" if v else "false"};\n')
                    info['consts'][cls][name] = 'Boolean'
                elif typ == 'Number':
                    f.write(f'constexpr double {name} = {float(v)!r};\n')
                    info['consts'][cls][name] = 'Number'
                else:
                    f.write(f'constexpr int {name} = {int(v)};\n')
                    info['consts'][cls][name] = 'int'
            info['tables'][cls] = []
            for name, vals in arrays[cls]:
                body = ', '.join(str(x) for x in vals)
                f.write(f'inline const std::vector<int> {name} = {{{body}}};\n')
                info['tables'][cls].append(name)
            f.write(f'}} // namespace k{cls}\n\n')
    with open(OUT_JSON, 'w', encoding='utf-8') as jf:
        json.dump(info, jf, indent=0)

    n_const = sum(len(v) for v in values.values())
    n_arr = sum(len(v) for v in arrays.values())
    print(f'{OUT}: {n_const} constants, {n_arr} tables')
    if unresolved:
        print('UNRESOLVED constants:', unresolved)
    if skipped_arrays:
        print('Skipped non-numeric tables:', ', '.join(skipped_arrays))


if __name__ == '__main__':
    main()
