// Hand-written parts of Drawing: everything in Drawing.as that is Flash-specific
// (initApp resource/event setup, Timer, mouse + keyboard events). The rest of Drawing
// is generated by tools/as3cpp.py into src/gen/Drawing.cpp.
#include <SDL.h>

#include "../engine/gfx.h"
#include "../gen/classes.h"

using namespace kDrawing;

void Drawing::setNative(Gfx* g, Audio* a, TextCache* t, const std::string& assets) {
    gfx = g;
    audio = a;
    text = t;
    assetDir = assets;
}

// Drawing.initApp (line 1912) without the Flash display list / event listeners.
void Drawing::initApp() {
    for (int i = 0; i < 8; ++i) PASSWORD[i] = false;
    nPasswordPos = 0;
    lib = new Lib(this, gfx, audio, text, assetDir);
    if (GAME_RELEASE) bPasswordLock = false;
    ASEANI.resize(160);
    ope = new Operation(this);
    touch = new TouchAction(this);
    key = new KeyAction(this);
    player = new Player(this);
    for (int i = 0; i < MAX_ENEMYNUM; ++i) ENEMY[i] = new Enemy(this);
    for (int i = 0; i < MAX_UNITNUM; ++i) UNIT[i] = new Unit(this);
    for (int i = 0; i < MAX_DESTINYICONNUM; ++i) DESTINYICON[i] = new DestinyIcon(this);
    bCreateKeyboardEvent = true;
    nBlurFrame = 0;
    lib->nLoadImgCount = 0;
    lib->bLoading = false;
    lib->loadEmbedImg();
    lib->resetClip();
    bFirstTitle = true;
    bEnding = false;
    bActive = true;
    bResume = false;
    bOkBtn = false;
    bSurvivalOkBtn = false;
    bNoBtn = false;
    bChangeChapter = false;
    bNextChapterBtn = false;
    bBeforeChapterBtn = false;
    bResumeBtn = false;
    bReplayBtn = false;
    bGiveUpBtn = false;
    bCardBtn = false;
    bEmblemBtn = false;
    bAchieveBtn = false;
    bRankingBtn = false;
    bAddGemBtn = false;
    bOptionBtn = false;
    bOtherWindow = false;
    bScreenDrag = false;
    bMoveLeftDrag = false;
    bMoveRightDrag = false;
    bCardOver = false;
    bEmblemOver = false;
    bAchieveOver = false;
    bRankingOver = false;
    bAppStoreBtn = false;
    bGooglePlayBtn = false;
    bKeyMove = false;
    nBtnFrame = 0;
    nTouchX = INITDATA;
    nTouchY = INITDATA;
    nTouchMoveX = INITDATA;
    nTouchMoveY = INITDATA;
    nKeyValue = INITDATA;
    nLcdWC = nLcdW >> 1;
    nLcdHC = nLcdH >> 1;
    if (!lib->loadFile(DB_OPTION, "paladog_option", INITDATA)) {
        lib->nMusicVolume = 3;
        lib->nEffectVolume = 3;
        lib->nSaveMusicVolume = lib->nMusicVolume;
        lib->nSaveEffectVolume = lib->nEffectVolume;
    }
    nSetTime = as3::getTimer();
    nFps = 0;
    _nFps = 0;
    nFpsSetTime = as3::getTimer();
    nLeakTime = 0;
    nLeakFrame = 0;
}

// Drawing.run (line 2073): one Timer tick.
void Drawing::runFrame(int leakFrames) {
    nLeakFrame = leakFrames;
    gfx->beginFrame();
    paint();
}

// Drawing.keyPress / keyRelease (line 2097).
void Drawing::keyDown(int flashKeyCode) { key->keyPress(flashKeyCode); }
void Drawing::keyUp(int flashKeyCode) { key->keyRelease(flashKeyCode); }

// Drawing.touchDownAction / touchUpAction / touchMoveAction (line 2115).
void Drawing::mouseDown(int x, int y) {
    nTouchX = x;
    nTouchY = y;
    touch->bUpEvent = false;
    touch->bDownEvent = true;
}

void Drawing::mouseUp(int x, int y) {
    nTouchX = x;
    nTouchY = y;
    touch->bDownEvent = false;
    touch->bUpEvent = true;
}

void Drawing::mouseMove(int x, int y) {
    nTouchMoveX = x;
    nTouchMoveY = y;
    touch->bMoveEvent = true;
}

// Drawing.sendServerLog (line 2462): analytics call, nothing to do natively.
void Drawing::sendServerLog(int, int, int) {}
